/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CloudUpload, LoaderCircle, Paperclip } from "lucide-react";
import {
  FileInput,
  FileUploader,
  FileUploaderContent,
  FileUploaderItem,
} from "@/components/ui/file-upload";
import { Switch } from "@/components/ui/switch";
import { useRouter, useSearchParams } from "next/navigation";
import SubmitBtn from "@/components/actions/SubmitBtn";
import { useGetCategories } from "@/features/category/api/queries";
import useScrollToTop from "@/hooks/useScrollToTop";
import { useCreateCategory } from "@/features/category/api/mutations";
import { generateSlug } from "@/lib/util/generateSlug";

const formSchema = z.object({
  category_level: z.string().optional(),
  parentId: z.string().min(1),
  name: z.string().min(1),
  slug: z.string().min(1),
  description: z.string().optional(),
  image: z.string().optional(),
  isActive: z.boolean().optional(),
});

export default function CategoryCreateForm() {
  useScrollToTop();
  const [files, setFiles] = useState<File[] | null>(null);
  const { mutate, isPending, isSuccess } = useCreateCategory();
  const searchParams = useSearchParams();
  const router = useRouter();
  const levelValue = searchParams.get("level"); // Get the "level" value
  const cateId = searchParams.get("cateId"); // Get the "level" value

  const dropZoneConfig = {
    maxFiles: 5,
    maxSize: 1024 * 1024 * 4,
    multiple: true,
  };

  const getLevelValue = () => {
    if (levelValue === "sub") {
      return "1";
    }
    if (levelValue === "last") {
      return "2";
    }
    return "0";
  };

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      isActive: true,
      category_level: getLevelValue(),
      parentId: cateId ? cateId : "0",
    },
  });

  const level = form.watch("category_level");
  const name = form.watch("name");

  const getLevelValueText = () => {
    if (level === "1") {
      return "sub";
    }
    if (level === "2") {
      return "last";
    }
    return "main";
  };

  const { data } = useGetCategories({
    type: level === "1" ? "main" : "sub",
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    const { category_level, parentId, ...others } = values;
    let data;
    if (parentId !== "0") {
      data = { ...others, parentId };
    } else {
      data = { ...others };
    }
    try {
      await mutate({ ...data, level: getLevelValueText() });
    } catch (error) {
      console.error("Form submission error", error);
    }
  }

  useEffect(() => {
    if (name) {
      const autoGeneratedSlug = generateSlug(name);
      form.setValue("slug", autoGeneratedSlug);
    } else {
      form.setValue("slug", ""); // Clear slug if name is empty
    }
  }, [name, form.setValue]);

  useEffect(() => {
    const currentLevel = searchParams.get("level");
    let newLevelParam = "main";

    if (level === "1") {
      newLevelParam = "sub";
    } else if (level === "2") {
      newLevelParam = "last";
    }

    if (currentLevel !== newLevelParam) {
      const newSearchParams = new URLSearchParams(searchParams.toString());
      newSearchParams.set("level", newLevelParam);
      router.replace(`?${newSearchParams.toString()}`);
    }
  }, [level, router, searchParams]);

  useEffect(() => {
    if (isSuccess) {
      form.reset({
        name: "",
        slug: "",
        description: "",
        isActive: true,
        category_level: getLevelValue(),
        parentId: cateId ? cateId : "0",
      });
    }
  }, [isSuccess]);

  return (
    <div className=" p-10">
      <h3>Create New Category</h3>
      <Form {...form}>
        <form
          onSubmit={form.handleSubmit(onSubmit)}
          className="space-y-3 py-10"
        >
          <div className=" grid grid-cols-1 xl:grid-cols-2 gap-5">
            <div className=" space-y-3">
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Name</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Category Name"
                        type="text"
                        {...field}
                        className="bg-white"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="slug"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Slug</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Slug"
                        type="text"
                        {...field}
                        className="bg-white"
                        readOnly
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Category description"
                        className="resize-none bg-white"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="isActive"
                render={({ field }) => (
                  <FormItem className="flex flex-row items-center justify-between rounded-lg border p-4 bg-white">
                    <div className="space-y-0.5">
                      <FormLabel>Is category active</FormLabel>
                    </div>
                    <FormControl>
                      <Switch
                        checked={field.value}
                        onCheckedChange={field.onChange}
                        aria-readonly
                      />
                    </FormControl>
                  </FormItem>
                )}
              />
            </div>
            <div className=" space-y-3">
              <FormField
                control={form.control}
                name="image"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Upload Category Image</FormLabel>
                    <FormControl>
                      <FileUploader
                        value={files}
                        onValueChange={setFiles}
                        dropzoneOptions={dropZoneConfig}
                        className="relative bg-background rounded-lg p-2"
                      >
                        <FileInput
                          id="fileInput"
                          className="outline-dashed outline-1 outline-slate-500"
                        >
                          <div className="flex items-center justify-center flex-col p-8 w-full ">
                            <CloudUpload className="text-gray-500 w-10 h-10" />
                            <p className="mb-1 text-sm text-gray-500 dark:text-gray-400">
                              <span className="font-semibold">
                                Click to upload
                              </span>
                              &nbsp; or drag and drop
                            </p>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                              SVG, PNG, JPG or GIF
                            </p>
                          </div>
                        </FileInput>
                        <FileUploaderContent>
                          {files &&
                            files.length > 0 &&
                            files.map((file, i) => (
                              <FileUploaderItem key={i} index={i}>
                                <Paperclip className="h-4 w-4 stroke-current" />
                                <span>{file.name}</span>
                              </FileUploaderItem>
                            ))}
                        </FileUploaderContent>
                      </FileUploader>
                    </FormControl>
                    <FormDescription>Select a file to upload.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="category_level"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Choose Category Level</FormLabel>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                    >
                      <FormControl>
                        <SelectTrigger className=" bg-white">
                          <SelectValue placeholder="Select a category level" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent className=" bg-white">
                        <SelectItem value="0">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-primary"></div>
                            Main Category (Level 1)
                          </div>
                        </SelectItem>
                        <SelectItem value="1">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-blue-600"></div>
                            Subcategory (Level 2)
                          </div>
                        </SelectItem>
                        <SelectItem value="2">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-green-600"></div>
                            Brand/Sub-subcategory (Level 3)
                          </div>
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              {Number(level) > 0 ? (
                <FormField
                  control={form.control}
                  name="parentId"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Choose Parent Category</FormLabel>
                      <Select
                        onValueChange={field.onChange}
                        defaultValue={field.value}
                      >
                        <FormControl>
                          <SelectTrigger className=" bg-white">
                            <SelectValue placeholder="Select a parent category" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent className=" bg-white">
                          {data?.map((item) => (
                            <SelectItem key={item.id} value={item.id}>
                              {item.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>

                      <FormMessage />
                    </FormItem>
                  )}
                />
              ) : null}
            </div>
          </div>

          <SubmitBtn isPending={isPending} />
        </form>
      </Form>
    </div>
  );
}
