/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CloudUpload, Paperclip } from "lucide-react";
import {
  FileInput,
  FileUploader,
  FileUploaderContent,
  FileUploaderItem,
} from "@/components/ui/file-upload";
import { Switch } from "@/components/ui/switch";
import toast from "react-hot-toast";
import {
  useGetCategories,
  useGetCategoryById,
} from "@/features/category/api/queries";
import useScrollToTop from "@/hooks/useScrollToTop";
import { useUpdateCategory } from "@/features/category/api/mutations";
import { useRouter } from "next/navigation";
import SubmitBtn from "../actions/SubmitBtn";
import { generateSlug } from "@/lib/util/generateSlug";

const formSchema = z.object({
  category_level: z.string().optional(),
  parentId: z.string(),
  name: z.string().min(1),
  slug: z.string().min(1),
  description: z.string().optional(),
  image: z.string().optional(),
  isActive: z.boolean().optional(),
});

export default function CategoryEditForm({ id }: { id: string }) {
  useScrollToTop();
  const router = useRouter();
  const [files, setFiles] = useState<File[] | null>(null);
  const { data: category, isLoading } = useGetCategoryById(id);

  const { mutate, isPending } = useUpdateCategory();

  const dropZoneConfig = {
    maxFiles: 5,
    maxSize: 1024 * 1024 * 4,
    multiple: true,
  };

  const getLevelValue = () => {
    if (category?.level === 1) {
      return "1";
    }
    if (category?.level === 2) {
      return "2";
    }
    return "0";
  };

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      category_level: getLevelValue(),
      parentId: category?.parentId || "",
      name: category?.name || "",
      slug: category?.slug || "",
      description: category?.description || "",
      image: category?.image || "",
      isActive: category?.isActive || false,
    },
  });

  const level = form.watch("category_level");
  const name = form.watch("name");

  const { data: categories } = useGetCategories({
    type: level === "1" ? "main" : "sub",
  });

  const getLevelValueText = () => {
    if (level === "1") {
      return "sub";
    }
    if (level === "2") {
      return "last";
    }
    return "main";
  };

  async function onSubmit(values: z.infer<typeof formSchema>) {
    const { category_level, parentId, ...others } = values;
    let data;
    if (level !== "0") {
      data = {
        ...others,
        parentId,
      };
    } else {
      data = {
        ...others,
      };
    }
    try {
      await mutate({
        id,
        data: { ...data, level: getLevelValueText() },
      });
      router.back();
    } catch (error) {
      console.error("Form submission error", error);
    }
  }

  useEffect(() => {
    if (name) {
      const autoGeneratedSlug = generateSlug(name);
      form.setValue("slug", autoGeneratedSlug);
    } else {
      form.setValue("slug", ""); // Clear slug if name is empty
    }
  }, [name, form.setValue]);

  useEffect(() => {
    if (category) {
      form.setValue("category_level", getLevelValue());
      form.setValue("parentId", category.parentId || "");
      form.setValue("name", category.name || "");
      form.setValue("slug", category.slug || "");
      form.setValue("description", category.description || "");
      form.setValue("image", category.image || "");
      form.setValue("isActive", category.isActive || false);
    }
  }, [category]);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <div className=" p-10">
      <h3>Edit Category</h3>
      <Form {...form}>
        <form
          onSubmit={form.handleSubmit(onSubmit)}
          className="space-y-3 py-10"
        >
          <div className=" grid grid-cols-1 xl:grid-cols-2 gap-5">
            <div className=" space-y-3">
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Name</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Category Name"
                        type="text"
                        className="bg-white"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="slug"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Slug</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Slug"
                        className="bg-white"
                        type="text"
                        {...field}
                        readOnly
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Category description"
                        className="resize-none bg-white"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="isActive"
                render={({ field }) => (
                  <FormItem className="flex flex-row items-center justify-between bg-white rounded-lg border p-4">
                    <div className="space-y-0.5">
                      <FormLabel>Is category active</FormLabel>
                    </div>
                    <FormControl>
                      <Switch
                        checked={field.value}
                        onCheckedChange={field.onChange}
                        aria-readonly
                      />
                    </FormControl>
                  </FormItem>
                )}
              />
            </div>
            <div className=" space-y-3">
              <FormField
                control={form.control}
                name="image"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Select File</FormLabel>
                    <FormControl>
                      <FileUploader
                        value={files}
                        onValueChange={setFiles}
                        dropzoneOptions={dropZoneConfig}
                        className="relative bg-background rounded-lg p-2"
                      >
                        <FileInput
                          id="fileInput"
                          className="outline-dashed outline-1 outline-slate-500"
                        >
                          <div className="flex items-center justify-center flex-col p-8 w-full ">
                            <CloudUpload className="text-gray-500 w-10 h-10" />
                            <p className="mb-1 text-sm text-gray-500 dark:text-gray-400">
                              <span className="font-semibold">
                                Click to upload
                              </span>
                              &nbsp; or drag and drop
                            </p>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                              SVG, PNG, JPG or GIF
                            </p>
                          </div>
                        </FileInput>
                        <FileUploaderContent>
                          {files &&
                            files.length > 0 &&
                            files.map((file, i) => (
                              <FileUploaderItem key={i} index={i}>
                                <Paperclip className="h-4 w-4 stroke-current" />
                                <span>{file.name}</span>
                              </FileUploaderItem>
                            ))}
                        </FileUploaderContent>
                      </FileUploader>
                    </FormControl>
                    <FormDescription>Select a file to upload.</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="category_level"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Choose Category Level</FormLabel>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                      disabled={category?.level !== 2}
                    >
                      <FormControl>
                        <SelectTrigger className=" bg-white">
                          <SelectValue placeholder="Select a category level" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent className="bg-white">
                        <SelectItem value="0">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-primary"></div>
                            Main Category (Level 1)
                          </div>
                        </SelectItem>
                        <SelectItem value="1">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-blue-600"></div>
                            Subcategory (Level 2)
                          </div>
                        </SelectItem>
                        <SelectItem value="2">
                          <div className="flex items-center gap-2">
                            <div className="w-3 h-3 rounded-full bg-green-600"></div>
                            Brand/Sub-subcategory (Level 3)
                          </div>
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
              {Number(level) > 0 ? (
                <FormField
                  control={form.control}
                  name="parentId"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Choose Parent Category</FormLabel>
                      <Select
                        onValueChange={field.onChange}
                        defaultValue={field.value}
                      >
                        <FormControl>
                          <SelectTrigger className=" bg-white">
                            <SelectValue placeholder="Select a parent category" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent className=" bg-white">
                          {categories?.map((item) => (
                            <SelectItem key={item.id} value={item.id}>
                              {item.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>

                      <FormMessage />
                    </FormItem>
                  )}
                />
              ) : null}
            </div>
          </div>

          <SubmitBtn isPending={isPending} title="Update" />
        </form>
      </Form>
    </div>
  );
}
